apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: wekan-pipeline
    name: wekan-pipeline
  name: wekan-pipeline
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Parallel
  source:
    git:
      uri: 'https://github.com/gil0109/SBC_DivApps'
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: apps/wekan/Jenkins_wekan.yaml
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers: []
