kind: Template
apiVersion: v1
metadata:
  name: Wekan
  annotations:
    description: ""
    tags: Wekan
    iconClass: icon-python
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: wekan
      annotations:
        description: "Keeps track of changes in the application image"
      labels:
        app: wekan
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        app: wekan
      name: wekan
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: 'wekan:latest'
      postCommit: {}
      resources:
        limits:
          cpu: '1'
          memory: 8Gi
        requests:
          cpu: '1'
          memory: 4Gi
      source:
        git:
          uri: 'https://github.com/wekan/wekan.git'
        type: Git
      strategy:
        dockerStrategy: {}
        type: Docker
      successfulBuildsHistoryLimit: 5
      triggers: []